spring:
  application:
    name: first-provider
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5 #本提供都每5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 #10秒不发心跳注册中心将本提供者删除
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
logging:
  level:
    com.netflix: debug